### ISSUE TITLE
Matcha.Spec.stream example from the documentation is throwing an exception regarding __emit_erl_test_result/1

### ISSUE THREAD

**Issue by BrianAdams** [christhekeele/matcha#68]
Trying to run the example for streaming

``` elixir
require Matcha

Matcha.spec do
  {amount, tax} when is_integer(amount) and amount < 0 -> {:charge, amount + tax}
end
|> Matcha.Spec.stream([
  {9001, 0},
  {-200, -2.50},
  {-3, -0.5},
  {:error, "bank was offline"},
  {100, 0},
  {-743, -16.0},
])
|> Stream.take(2)
|> Enum.to_list
```

expected a list but instead get an exception

```
** (FunctionClauseError) no function clause matching in Matcha.Context.FilterMap.__emit_erl_test_result__/1    
    
    The following arguments were given to Matcha.Context.FilterMap.__emit_erl_test_result__/1:
    
        # 1
        nil
    
    Attempted function clauses (showing 2 out of 2):
    
        def __emit_erl_test_result__({:returned, result})
        def __emit_erl_test_result__({:no_return})
    
    (matcha 0.1.10) Matcha.Context.FilterMap.__emit_erl_test_result__/1
    (matcha 0.1.10) lib/matcha/context.ex:308: Matcha.Context.do_stream_test/3
    (elixir 1.15.7) lib/stream.ex:990: Stream.do_transform_user/6
    (elixir 1.15.7) lib/enum.ex:4387: Enum.reverse/1
    (elixir 1.15.7) lib/enum.ex:3704: Enum.to_list/1
    #cell:mia6pqqhcqijxsqnahu2cflh2cnoehht:18: (file)
```

System.version()
"1.15.7"

System.otp_release()
"26"

matcha 0.1.10

**Comment by christhekeele** [comment]
😅 Went to look at this and [found a #FIXME note-to-self](https://github.com/christhekeele/matcha/blob/latest/lib/matcha/spec.ex#L163) immediately preceding this example.

I've debated removing this function entirely from Matcha for a while, as it is not useful in practice as far as I'm aware (and explains why it's been able to be broken for 2 years), so I'm curious as to your use-case!

---

### Context

In general the `Matcha.Spec` functions are broken down into two categories: validation, and experimentation. The experimentation functions like `Spec.call` (against a single target) and `Spec.run` (against a list of them) are meant to let you test out a spec created with `Matcha.spec` before actual usage in `Matcha.Table` and `Matcha.Trace` APIs.

Using matchspecs against ***in-memory runtime data*** with these functions does not confer a performance advantage over normal `Enum.map`/`Enum.filter` functions (in practice, about 1.2x times slower I think, last time I benchmarked). This is because the `Enum` functions are highly optimized around in-memory data, and `Matcha` has to do extra work in the experimentation functions to honor matchspec not-in-memory table/tracing semantics ***and*** make them behave similar to `Enum.map` semantics.

This leaves `Spec.stream` in an awkward position. The performance for it is worse still, because it has to do this extra work every time an element is emitted (effectively invoking `Spec.call` on every element), instead of at once on the full set of inputs/outputs (effectively calling `Spec.run`). And `Matcha` isn't really meant to be used in this way against datasets large enough to merit `Stream` usage: `Stream.map`/`Stream.filter` should always be preferred.

So I've been on the fence for a while about whether or not to leave `Spec.stream` around, as it encourages mis-use of match specs.
